/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData akk_cross = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData akk_minus = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData akk_ok = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytics = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData athletes = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diary = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData end = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exercises = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goal = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_hip = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_forearm = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_hip = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_photo = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_shoulder = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_training = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_off = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_on = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notmy_training = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photos = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_small = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quit = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_forearm = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_kettlebell = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_shoulder = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_cross = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData start = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waist = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avatar = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hips = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neck = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoulders = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_shin = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_shin = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
