name: onlygym
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  eticon_api: ^2.0.4
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  auto_route: ^7.7.0
  flutter_svg: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  get_it: ^7.6.0
  #flutter_sentry: ^0.5.1
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.2
  firebase_core: ^1.22.0
  firebase_messaging: 12.0.3
  permission_handler: ^10.2.0
  dio: ^4.0.6
  flutter_screenutil: ^5.7.0
  file_picker: ^5.3.0
  qr_flutter: ^4.1.0
  intl: ^0.17.0
  image_picker: ^1.0.1
  qr_code_scanner: ^1.0.1
  carousel_slider: ^4.2.1
  regexed_validator: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^7.2.0


flutter:
  uses-material-design: true
  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: PtRoot
      fonts:
         - asset: assets/fonts/pt-root-ui_bold.ttf
           weight: 700
         - asset: assets/fonts/pt-root-ui_medium.ttf
           weight: 600
         - asset: assets/fonts/pt-root-ui_regular.ttf
           weight: 500
         - asset: assets/fonts/pt-root-ui_light.ttf
           weight: 400

    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf


