name: onlygym
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  eticon_api: ^2.0.4
  flutter_svg: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_sentry: ^0.5.1
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.2
  firebase_core: ^1.22.0
  firebase_messaging: 12.0.3
  permission_handler: ^10.2.0
  dio: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

#flutter_native_splash:
#  image: assets/images/splash_image.png
#  color: "#000000"
#  android: true
#  ios: true
#  android_12:
#    image: assets/images/android12splash.png
#    color: "#000000"
#    icon_background_color: "#000000"
#    image_dark: assets/images/android12splash.png
#    color_dark: "#000000"
#    icon_background_color_dark: "#000000"
#
#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icons/icon.png"